version: '3.0'
services:

  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: ebudaev/mirror_backend:v1
    container_name: mirror_backend
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: ebudaev/mirror_frontend:v1
    container_name: mirror_frontend
    restart: always
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
    environment:
      - REACT_APP_PROD_DOMAIN='http://62.84.119.86/'
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  static_value:
  media_value:
