# Generated by Django 3.2.5 on 2021-08-19 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, choices=[('Круглая', 'Круглая'), ('Овальная', 'Овальная'), ('Прямоугольная', 'Прямоугольная'), ('Фигурная', 'Фигурная')], max_length=64, null=True, verbose_name='Форма')),
                ('mirror_material', models.CharField(blank=True, choices=[('Влагостойкое серебряное зеркало', 'Влагостойкое серебряное зеркало')], max_length=64, null=True, verbose_name='Материал зеркала')),
                ('frame_material', models.CharField(blank=True, choices=[('Основа МДФ', 'Основа МДФ'), ('Полирезин', 'Полирезин')], max_length=64, null=True, verbose_name='Материал рамы')),
                ('frame_color', models.CharField(blank=True, choices=[('Античное золото', 'Античное золото'), ('Античное серебро', 'Античное серебро'), ('Бронза', 'Бронза'), ('Золото', 'Золото'), ('Латунь', 'Латунь'), ('Серебро', 'Серебро'), ('Хром', 'Хром')], max_length=64, null=True, verbose_name='Цвет рамы')),
                ('height_with_frame', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота с рамой')),
                ('width_with_frame', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ширина с рамой')),
                ('height_without_frame', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Высота без рамы')),
                ('width_without_frame', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ширина без рамы')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Вес')),
                ('is_faced', models.BooleanField(blank=True, default=True, null=True, verbose_name='Наличие фацета')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название для каталога', max_length=255, verbose_name='Название каталога')),
                ('image', models.ImageField(blank=True, help_text='Добавьте изображение каталогу', null=True, upload_to='', verbose_name='Изображение каталога')),
                ('catalog_slug', models.SlugField(help_text='Задайте уникальный URL адрес названию каталога', max_length=255, unique=True, verbose_name='URL каталога')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название для категории', max_length=255, verbose_name='Имя категории')),
                ('image', models.ImageField(blank=True, help_text='Добавьте изображение к посту', null=True, upload_to='', verbose_name='Изображение категории')),
                ('category_slug', models.SlugField(help_text='Задайте уникальный URL адрес категории', max_length=255, unique=True, verbose_name='URL категории')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('catalog', models.ForeignKey(help_text='Пожалуйста, выберите  каталог', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.catalog', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование товара')),
                ('product_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL продукта')),
                ('brand', models.CharField(blank=True, choices=[('Mirror Look', 'Mirror Look')], max_length=64, null=True, verbose_name='Бренд')),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение продукта')),
                ('product_photo1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('count_in_stock', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Кол-во товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Рейтинг')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Продукт и атрибут',
                'verbose_name_plural': 'Продукты и атрибуты',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='store.ProductAttribute', to='store.Attribute', verbose_name='Атрибуты'),
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.catalog', verbose_name='Каталог'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='store.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт корзины',
                'verbose_name_plural': 'Продукты корзины',
            },
        ),
    ]
