# Generated by Django 3.2.5 on 2022-02-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='frame_color',
            field=models.CharField(blank=True, choices=[('Античная бронза', 'Античная бронза'), ('Античное золото', 'Античное золото'), ('Античное серебро', 'Античное серебро'), ('Бронза', 'Бронза'), ('Золото', 'Золото'), ('Латунь', 'Латунь'), ('Никель', 'Никель'), ('Серебро', 'Серебро'), ('Сталь полированная', 'Сталь полированная'), ('Хром', 'Хром'), ('Черный', 'Черный'), ('Шампань', 'Шампань')], max_length=64, null=True, verbose_name='Цвет рамы'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='frame_material',
            field=models.CharField(blank=True, choices=[('Дерево', 'Дерево'), ('Дерево/Полирезин', 'Дерево/Полирезин'), ('Металл', 'Металл'), ('Основа МДФ', 'Основа МДФ'), ('Основа МДФ влагостойкий', 'Основа МДФ влагостойкий'), ('Основа МДФ/Экокожа', 'Основа МДФ/Экокожа'), ('Полирезин', 'Полирезин'), ('Полиуретан', 'Полиуретан')], max_length=64, null=True, verbose_name='Материал рамы'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='mirror_material',
            field=models.CharField(blank=True, choices=[('Влагостойкое серебряное зеркало', 'Влагостойкое серебряное зеркало'), ('Влагостойкое серебряное сферическое зеркало', 'Влагостойкое серебряное сферическое зеркало')], max_length=64, null=True, verbose_name='Материал зеркала'),
        ),
    ]
