# Generated by Django 3.2.5 on 2021-08-09 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consoles', to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mirror',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors', to='store.category', verbose_name='Категория'),
        ),
    ]
