# Generated by Django 3.2.5 on 2022-01-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_bought',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Купленное кол-во товара'),
        ),
    ]
