# Generated by Django 3.2.5 on 2021-08-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210819_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
    ]
