# Generated by Django 3.2.5 on 2021-07-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210718_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mirror',
            old_name='weight_with_frame',
            new_name='width_with_frame',
        ),
        migrations.RenameField(
            model_name='mirror',
            old_name='weight_without_frame',
            new_name='width_without_frame',
        ),
    ]
