# Generated by Django 3.2.5 on 2021-09-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий для курьера'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='entrance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='intercom',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Домофон'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
