# Generated by Django 3.2.5 on 2021-10-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
    ]
