# Generated by Django 3.2.5 on 2021-10-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211026_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',), 'verbose_name': 'Комментарий к отзыву', 'verbose_name_plural': 'Комментарии к отзыву'},
        ),
        migrations.CreateModel(
            name='ReviewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='store.review', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Данные пользователя, который оставил отзыв',
                'verbose_name_plural': 'Данные пользователей, которые оставили отзывы',
            },
        ),
    ]
