export enum ActionTypes {
  ORDER_SHIPPING_ADDRESS_SAVE = "cart/ORDER_SHIPPING_ADDRESS_SAVE",
  ORDER_CREATE = "cart/ORDER_CREATE",
  FETCH_ORDER_SHIPPING_ADDRESS_SAVE = "cart/FETCH_ORDER_SHIPPING_ADDRESS_SAVE",
  FETCH_ORDER_CREATE = "cart/FETCH_ORDER_CREATE",
}
