export enum ActionTypes {
  ORDER_CREATE = "order/ORDER_CREATE",
  ORDER_RECIPIENT_SAVE = "order/ORDER_RECIPIENT_SAVE",
  ORDER_SHIPPING_ADDRESS_SAVE = "order/ORDER_SHIPPING_ADDRESS_SAVE",
  FETCH_ORDER_CREATE = "order/FETCH_ORDER_CREATE",
  FETCH_ORDER_RECIPIENT_SAVE = "order/FETCH_ORDER_RECIPIENT_SAVE",
  FETCH_ORDER_SHIPPING_ADDRESS_SAVE = "order/FETCH_ORDER_SHIPPING_ADDRESS_SAVE",
  FETCH_ORDER_SEND_TO_EMAIL = "order/FETCH_ORDER_SEND_TO_EMAIL",
}
