export const LOGOUT = "account/LOGOUT";
export const AUTHENTICATED_SUCCESS = "account/AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "account/AUTHENTICATED_FAIL";
export const PASSWORD_RESET_SUCCESS = "account/PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "account/PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS =
  "account/PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL =
  "account/PASSWORD_RESET_CONFIRM_FAIL";

export enum ActionTypes {
  ACTIVATION_SUCCESS = "account/ACTIVATION_SUCCESS",
  ACTIVATION_FAIL = "account/ACTIVATION_FAIL",
  AUTHENTICATED_SUCCESS = "account/AUTHENTICATED_SUCCESS",
  AUTHENTICATED_FAIL = "account/AUTHENTICATED_FAIL",
  LOGIN = "account/LOGIN",
  LOGOUT = "account/LOGOUT",
  PASSWORD_RESET_SUCCESS = "account/PASSWORD_RESET_SUCCESS",
  PASSWORD_RESET_FAIL = "account/PASSWORD_RESET_FAIL",
  PASSWORD_RESET_CONFIRM_FAIL = "account/PASSWORD_RESET_CONFIRM_FAIL",
  SET_USER = "account/SET_USER",
  SET_USER_TOKEN = "account/SET_USER_TOKEN",
  SIGNUP = "account/SIGNUP",
  SIGNUP_USER = "account/SIGNUP_USER",
}
