export enum ActionTypes {
  BASKET_ADD_ITEM = "basket/BASKET_ADD_ITEM",
  BASKET_REMOVE_ITEM = "basket/BASKET_REMOVE_ITEM",
  FETCH_BASKET_ADD_ITEM = "basket/FETCH_BASKET_ADD_ITEM",
  FETCH_BASKET_REMOVE_ITEM = "basket/FETCH_BASKET_REMOVE_ITEM",
}
