export enum ActionTypes {
  CART_CREATE = "cart/CART_CREATE",
  CART_INIT = "cart/CART_INIT",
  CART_SET = "cart/CART_SET",
  CART_ADD_ITEM = "cart/CART_ADD_ITEM",
  CART_ITEM_DECREMENT = "cart/CART_ITEM_DECREMENT",
  CART_ITEM_INCREMENT = "cart/CART_ITEM_INCREMENT",
  FETCH_CART_ADD_ITEM = "cart/FETCH_CART_ADD_ITEM",
  FETCH_CART_ITEM_DECREMENT = "cart/FETCH_CART_ITEM_DECREMENT",
  FETCH_CART_ITEM_INCREMENT = "cart/FETCH_CART_ITEM_INCREMENT",
}
